from __future__ import annotations

from . import mat_wrappers as _mat_wrappers


_DENSE_EXPORTS = (
    "arb_mat_matmul_batch_fixed_mode",
    "arb_mat_matmul_batch_padded_mode",
    "arb_mat_permutation_matrix_batch_fixed_mode",
    "arb_mat_permutation_matrix_batch_padded_mode",
    "arb_mat_transpose_batch_fixed_mode",
    "arb_mat_transpose_batch_padded_mode",
    "arb_mat_diag_batch_fixed_mode",
    "arb_mat_diag_batch_padded_mode",
    "arb_mat_diag_matrix_batch_fixed_mode",
    "arb_mat_diag_matrix_batch_padded_mode",
    "arb_mat_matvec_batch_fixed_mode",
    "arb_mat_matvec_batch_padded_mode",
    "arb_mat_banded_matvec_batch_fixed_mode",
    "arb_mat_banded_matvec_batch_padded_mode",
    "arb_mat_solve_batch_fixed_mode",
    "arb_mat_solve_batch_padded_mode",
    "arb_mat_inv_batch_fixed_mode",
    "arb_mat_inv_batch_padded_mode",
    "arb_mat_triangular_solve_batch_fixed_mode",
    "arb_mat_triangular_solve_batch_padded_mode",
    "arb_mat_lu_batch_fixed_mode",
    "arb_mat_lu_batch_padded_mode",
    "arb_mat_lu_solve_batch_fixed_mode",
    "arb_mat_lu_solve_batch_padded_mode",
    "arb_mat_qr_batch_fixed_mode",
    "arb_mat_qr_batch_padded_mode",
    "arb_mat_det_batch_fixed_mode",
    "arb_mat_det_batch_padded_mode",
    "arb_mat_trace_batch_fixed_mode",
    "arb_mat_trace_batch_padded_mode",
    "arb_mat_sqr_batch_fixed_mode",
    "arb_mat_sqr_batch_padded_mode",
    "arb_mat_norm_fro_batch_fixed_mode",
    "arb_mat_norm_fro_batch_padded_mode",
    "arb_mat_norm_1_batch_fixed_mode",
    "arb_mat_norm_1_batch_padded_mode",
    "arb_mat_norm_inf_batch_fixed_mode",
    "arb_mat_norm_inf_batch_padded_mode",
    "acb_mat_matmul_batch_fixed_mode",
    "acb_mat_matmul_batch_padded_mode",
    "acb_mat_permutation_matrix_batch_fixed_mode",
    "acb_mat_permutation_matrix_batch_padded_mode",
    "acb_mat_transpose_batch_fixed_mode",
    "acb_mat_transpose_batch_padded_mode",
    "acb_mat_conjugate_transpose_batch_fixed_mode",
    "acb_mat_conjugate_transpose_batch_padded_mode",
    "acb_mat_diag_batch_fixed_mode",
    "acb_mat_diag_batch_padded_mode",
    "acb_mat_diag_matrix_batch_fixed_mode",
    "acb_mat_diag_matrix_batch_padded_mode",
    "acb_mat_matvec_batch_fixed_mode",
    "acb_mat_matvec_batch_padded_mode",
    "acb_mat_banded_matvec_batch_fixed_mode",
    "acb_mat_banded_matvec_batch_padded_mode",
    "acb_mat_solve_batch_fixed_mode",
    "acb_mat_solve_batch_padded_mode",
    "acb_mat_inv_batch_fixed_mode",
    "acb_mat_inv_batch_padded_mode",
    "acb_mat_triangular_solve_batch_fixed_mode",
    "acb_mat_triangular_solve_batch_padded_mode",
    "acb_mat_lu_batch_fixed_mode",
    "acb_mat_lu_batch_padded_mode",
    "acb_mat_lu_solve_batch_fixed_mode",
    "acb_mat_lu_solve_batch_padded_mode",
    "acb_mat_qr_batch_fixed_mode",
    "acb_mat_qr_batch_padded_mode",
    "acb_mat_det_batch_fixed_mode",
    "acb_mat_det_batch_padded_mode",
    "acb_mat_trace_batch_fixed_mode",
    "acb_mat_trace_batch_padded_mode",
    "acb_mat_sqr_batch_fixed_mode",
    "acb_mat_sqr_batch_padded_mode",
    "acb_mat_norm_fro_batch_fixed_mode",
    "acb_mat_norm_fro_batch_padded_mode",
    "acb_mat_norm_1_batch_fixed_mode",
    "acb_mat_norm_1_batch_padded_mode",
    "acb_mat_norm_inf_batch_fixed_mode",
    "acb_mat_norm_inf_batch_padded_mode",
)


for _name in _DENSE_EXPORTS:
    globals()[_name] = getattr(_mat_wrappers, _name)


__all__ = list(_DENSE_EXPORTS)
